[phases.setup]
pythonVersion = "3.10"

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "rasa run --enable-api --cors \"*\""